### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by davidbrown2324** [weinerlab/mtk_primer_generator#6]
This is incredibly useful software. Your code has so few dependencies it could be put on jupyter colabratories allowing people with no coding experience to design primers online.

Please consider adding a license to this repo. There is some good advice here.
[Real Python Choose a License](https://choosealicense.com/)

**Comment by tlnagy** [comment]
Fixed by 3b387900c6e175898397c7a64673822bfc0e453c

**Comment by davidbrown2324** [comment]
Thanks. If you ever want to share this with people who don't even have python installed you can use [this](https://colab.research.google.com/drive/1Qk9TUiJZ1HSmoUgxfqHfX28T_8vsQgP_)
